/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Amine Hosseini (https://sketchfab.com/suburbandigital)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chess-piece-queen-e1bd054f088e4c928740c4989a4a3a41
Title: Chess Piece Queen
*/

import React, { } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/chess_piece_queen.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        // @ts-expect-error : pls
        geometry={nodes.queen_copy19_lambert4_0.geometry}
        material={materials.lambert4}
        position={[-7.671, 0, 7.592]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={2.54}
      />
    </group>
  )
}

useGLTF.preload('/chess_piece_queen.glb')
